### ISSUE TITLE
Удаление группы полей в секции приводит к скрытию всех дочерних .rcl-areas-manager

### ISSUE THREAD

**Issue by Preci1** [plechev-64/wp-recall-current#1]
https://github.com/plechev-64/wp-recall-current/blob/ea127d1389fc003a2a7e503be16b0ef9bbad952c/admin/assets/scripts.js#L701

Если в секции есть 3 группы полей, то при удалении 1-ой из них пропадает возможность удалить другие, до сохранения изменений и перезагрузки страницы.

Для фикса надо изменить условие на
`if ( countAreas === 1 ) {`

При этом не ясно нужно ли вообще это условие, т.к. при сохранении и обновлении страницы, даже в секции осталась 1 группа полей - ее все равно можно удалить.

**Comment by plechev-64** [comment]
пока удалю вообще это условие, позже продумаю соответствующую процедуру удаления
