### ISSUE TITLE
Не проходит валидация checkbox поля

### ISSUE THREAD

**Issue by Preci1** [plechev-64/wp-recall-current#10]
https://github.com/plechev-64/wp-recall-current/blob/bbf37453fb00c8b31a4842afdda63382c62aec20/assets/js/core.js#L1010

Если в форме публикации есть обязательное checkbox поле, то для прохождения валидации требуется выделить все пункты.

Для исправления надо заменить проверку на такую же как и у поля radio

`if ( jQuery( 'input[name="' + field.attr( 'name' ) + '"]:checked' ).val() )`

**Comment by plechev-64** [comment]
проверил на последней версии плагина, проблемы не заметил

**Comment by Preci1** [comment]
Возможно проблема только для поля checkbox у меток.

Если в этом условии добавить console.log(field) - то в консоль выводятся все поля-чекбоксы, т.е. если хотя бы 1 будет не checked - то валидация не проходит

**Comment by plechev-64** [comment]
не пойму как проблему повторить, делаю обязательным произвольное поле чекбоксов и поле меток с несколькими метками и то и другое поле допускают указание только одного значения, далее валидация проходит, запись публикуется

**Comment by Preci1** [comment]
В форме должно быть только 1 поле с чекбоксами - метки

Тогда проблема есть. Если будет еще какое-либо поле с чекбоксами - проблемы не будет

**Comment by plechev-64** [comment]
в последнем обновлении должно быть исправлено

**Comment by Preci1** [comment]
Проблема все еще есть

По крайней мере при публикации задания Freelance nextgen - там по стандарту только 1 поле с чекбоксами - выбор меток

В итоге когда проверка доходит до сюда

https://github.com/plechev-64/wp-recall-current/blob/bbf37453fb00c8b31a4842afdda63382c62aec20/assets/js/core.js#L1010

Если хотя бы 1 чекбокс не выбран - возвращается false. т.е. там каждое чекбокс поле проверяется отдельно, в итоге получается что надо выбрать все. Решение которое я предлагал в 1ом посте - работает. 

Почему проблема пропадает если добавить любое другое чекбокс поле, что бы их было 2 - я так и не разобрался

**Comment by plechev-64** [comment]
спасибо, использую предложенное тобой решение
