### ISSUE TITLE
Улучшение кеширования для rcl_get_time_user_action

### ISSUE THREAD

**Issue by Preci1** [plechev-64/wp-recall-current#3]
https://github.com/plechev-64/wp-recall-current/blob/edd15d2317ffc6fbdbdc619f1fab41bfe641b400/functions/frontend.php#L496-L513

1. Некорректное формирование $cachekey

Иногда $user_id приходит как число, а иногда как строка - в итоге $cachekey для таких случаев формируется разный

Если $user_id число: ["rcl_get_time_user_action",1]
Если $user_id строка: ["rcl_get_time_user_action","1"]

Корректное формирования ключа:
`$cachekey	 = json_encode( array( 'rcl_get_time_user_action', (int) $user_id ) );`

2. Если по какой-то причине данных о посещении для пользователя нет, то кеш не срабатывает  - в кеш пишется NULL, а это не true, а значит запрос повторится.

Предлагаю после

`$action = $wpdb->get_var(...`

добавить

```
if(!$action) {
	$action = '0000-00-00 00:00:00';
}
```
В принципе второй пункт, не обязательный, возможно это только у меня есть юзеры для которых нет записи о активности

**Comment by plechev-64** [comment]
Спасибо!
