### ISSUE TITLE
Непонятки с кешированием в Rcl_Query

### ISSUE THREAD

**Issue by Preci1** [plechev-64/wp-recall-current#4]
https://github.com/plechev-64/wp-recall-current/blob/b68bb5fc89c376247ea774a85b88cbf00fdfe61c/classes/query/class-rcl-query.php#L500

**1.** Непонятки с переменной $cache - она используется и для передачи параметра кеширования и для получения кеша - в итоге если данных в кеше нет - они не добавятся туда, т.к. в $cache присвоится false и проверка на добавление кеша не пройдет. Думаю надо параметр в методе переименовать в  $use_cache (и дальше в коде) - если я правильно понял его назначение

**2.** Например при получении рейтинга юзера в этот метод передается "cache", но затем идет проверка if($this->cache) - для чего она? Это свойство же устанавливается только у родителя, и нужно, как я понял, только для старых запросов. т.е. оно всегда в данном методе будет false

**3.** Стоит поменять $cacheKey

`$cachekey	 = json_encode( $query );`
на
`$cachekey	 = md5(json_encode( $query ));`

А то там получаются ключи по 300 символов, мне кажется это перебор.

**4.** Проверка есть ли данные в кеше
```
if ( $cache )
	return $cache;
```
В кеше может лежать '0' - например для рейтинга стоит заменить проверку на:

```
if ( $cache !== false )
	return $cache;
```

**Comment by plechev-64** [comment]
Все верно, спасибо!
