### ISSUE TITLE
Rcl_Query - дефолтное значение для select

### ISSUE THREAD

**Issue by Preci1** [plechev-64/wp-recall-current#7]
https://github.com/plechev-64/wp-recall-current/blob/898178a0ea74e1897c56db24823ae20166f78490/classes/query/class-rcl-query.php#L173

Если в select ничего не указать - будет ошибка, т.е. если мне нужны все результаты - надо обязательно указывать в select true или пустой массив - это не удобно.

Думаю стоит добавить в метод для параметра $select значение по-умолчанию как true или array(), тогда если нужны все результаты можно будет вызывать просто ->select()

**Comment by plechev-64** [comment]
В методе get_sql() есть проверка, если массив 'select' пуст или отсутствует, то, производиться выборка со всех столбцов, т.е. если вообще метод select() не вызывать, то должна сработать выборка по всем столбцам. Так не работает?

**Comment by Preci1** [comment]
Если ->select() не указывать, то да, работает. Но я даже не думал о таком. А с пустым ->select() вылезает ошибка 'too few arguments'

**Comment by plechev-64** [comment]
согласен, изначально также подразумевалось такое применение
