### ISSUE TITLE
При отправке формы не подхватывается значение tinymce

### ISSUE THREAD

**Issue by Preci1** [plechev-64/wp-recall-current#9]
https://github.com/plechev-64/wp-recall-current/blob/2a290a0af5e337dccfa197d568e704deba89a33f/assets/js/core.js#L669

Если сделать форму через rcl_get_form с tinymce редактором, то при отправке формы не берется значение редактора.
Для фикса можно вызывать tinyMCE.triggerSave(); перед сериализацией формы

**Comment by plechev-64** [comment]
спасибо, поправил
